language: node_js
node_js: node
cache:
  directories:
     - node_modules
deploy:
  provider: heroku
  api_key:
    secure: db09bbe3-c0c6-41cb-8047-f1e88f42e92c
  app: glacial-ridge-95298
  on:
    repo: FranciaMoran/Musician_Mashup